### ISSUE TITLE
[Fabric]: Attach CLI to already running peer

### ISSUE THREAD

**Issue by bafsunsu** [hyperledger/bevel#1226]
**Is your feature request related to a problem? Please describe.**
For a already running fabric network it would be good to have an option to attach CLI container that represents an existing peer, in case the CLI was not enabled while provisioning the network and peer.

**Describe the solution you'd like**
A Playbook that takes previous network.yaml as a input and for each peer having peer.cli as enabled it creates a CLI pod if not already present.
The playbook creates the required deployment files and waits for the newly added peer-cli pod to start running before the job is completed

**Describe alternatives you've considered**
manually running the create/cli_pod task and manually verifying the status of peer-cli pod

**Additional context**

**Comment by suvajit-sarkar** [comment]
Hi @bafsunsu, any updates on this issue ?

**Comment by manikanta-darsi** [comment]
Please assign it to me.
