### ISSUE TITLE
Upgrade Flux from v1 to v2 (Gitops)

### ISSUE THREAD

**Issue by sivaramsk** [hyperledger/bevel#1283]
The flux v1 version being used by BAF has been on maintenance mode for sometime. Flux v2 is a logical choice as BAF is already using v1 and there migration path described in the project from v1 to v2. 

Additional Context:
 - https://github.com/fluxcd/flux/issues/3320
 - https://toolkit.fluxcd.io/guides/helm-operator-migration/

**Comment by suvajit-sarkar** [comment]
hi @sivaramsk any updates on this ?

**Comment by sivaramsk** [comment]
Sorry @suvajit-sarkar - I started working on this and got side tracked with my day work. I had a list of questions on the upgrade, will update the ticket shortly with those and will also join your next Sprint planning to discuss how to proceed with this.

**Comment by sivaramsk** [comment]
One of the major question that came to me was - how much of backward compatibility should I think about when I work on this? Since I have not really tried upgrading any of my cluster, how should I handle the backward compatibility? 

From the testing I did to understand V2, it looks to be quite different (at least to my current understanding), so, it might be a bit easier to do this as breaking change rather than trying to make it compatible with older version. Another approach I was thinking is, may be we can have both the version supported and control it from network.yaml - have a flag to indicate whether you want to stick with the v1, but that would increase the testing effort to test both v1 and v2. 

This exactly the place I stopped my work last time when I started, I would appreciate your feedback on how to proceed on this.

**Comment by sownak** [comment]
@sivaramsk Thanks for getting back. For major upgrades, we do not maintain older version. So, if v2 is the way forward, we will only maintain that. And as this is a big change, i.e. all platforms need to be tested, we can create a long running feature branch and when all platforms are tested only then merge to develop/master.

**Comment by sivaramsk** [comment]
Thanks @sownak. Will update this ticket on my plan on how approach this feature.

**Comment by sivaramsk** [comment]
This feature looks much more complex than it initially looked to me. Following is a break up of tasks I am considering for this feature broadly.

1. Installation of Flux V2 by adding the flux binary in the baf-build container and 
2. Bootstrap the flux v2 in to the kubernetes cluster through the flux binary. (The folder structure used in v2 seems lot difference from v1, so, I am yet to fully understand the changes needed to make it work for BAF folder structure).
3. Migrate Hyperledger Fabric code to Flux V2.

**Comment by sivaramsk** [comment]
@sownak @suvajit-sarkar can someone help in creating a new branch for this feature. I could only raise the PR against created branches, but not create a new branch itself.

**Comment by sivaramsk** [comment]
This feature looks a bit more complex than it initially looked to me. I was able to install and bootstrap the flux_v2 in to the environment, but the biggest issue comes from the flux's use of kustomize internally. Kustomize looks not very straight forward to use when you have to create the yamls dynamically. Each folder that is used for deployment has a file called kustomization.yaml and when you create a new folder for deployment like "releases/new_release/org1/peer/release.yaml" - this folder have to be explicitly added to the root folder's kustomization.yaml. 

I guess I have to write a wrapper script to add the new folder in to the kustomization.yaml to make it work. Will keep updating here on the progress.

**Comment by sivaramsk** [comment]
Sorry guys, my bandwidth did not allow me work on this at all. Can someone take this over for me please?

@suvajit-sarkar

**Comment by hoang-innomizetech** [comment]
Would love if we have this change implemented. Looking forward to hearing if we have someone can support on this feature

**Comment by suvajit-sarkar** [comment]
Sure, no problem.. will check if we can prioritize this in the coming sprint

**Comment by suvajit-sarkar** [comment]
Closing this issue, flux v2 is on release please use latest branches for flux v2 support
