### ISSUE TITLE
Setup Prometheus on Kubernetes

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#1416]
### Description
As a Kubernetes operator I want to automatically add Prometheus on the Kubernetes cluster so that I can add monitoring for different Blockchain platforms.

### Acceptance Criteria
1. Add prometheus chart
2. Deploy prometheus from shared playbooks so that all platforms deploy prometheus.
3. Prometheus enablement, passwords must be provided via network.yaml
4. Ensure one Prometheus deployment per cluster

**Comment by saurabhkumarkardam** [comment]
I will check this.
