### ISSUE TITLE
Fabric - CA certificate refresh

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/bevel#1429]
**Is your feature request related to a problem? Please describe.**
Hyperledger Fabric uses Certificate Authorities and the Certificates issued by them to enable permissions. Certificates have limited time validity, they will eventually expire one day. There shall be option through Blockchain Automation Framework to re-issue a new set of identities to each of the component (associated with an organization), when the root certificate is expiring.

Root certificate refresh may require updating core component MSPs, channel configuration, user identities etc.

**Describe the solution you'd like**
An option from BAF to refresh the root CA's information for an organization that is specified via input network configuration.

**Describe alternatives you've considered**
Manual process

**Additional context**
NA

**Comment by sownak** [comment]
@arsulegai @sauveergoel Seems someone is asking for this one. Is this mergeable?

**Comment by arsulegai** [comment]
I’ll confirm back on this. It was too complex to automate the workflow for orderer root CA refresh. However, peer mode refreshes should be good.

**Comment by suvajit-sarkar** [comment]
Hi @sauveergoel, any updates on this ?

**Comment by mgCepeda** [comment]
I´ll take this isue

**Comment by arsulegai** [comment]
@nidhi-singh02 please check if there are inputs/learnings you can share with @mgCepeda.

**Comment by nidhi-singh02** [comment]
> 

Sure Arun, will share my learnings. @mgCepeda Happy to connect on Discord, my username is nidzi#8568.
