### ISSUE TITLE
Enable support for Fabric Private Chaincode

### ISSUE THREAD

**Issue by mbrandenburger** [hyperledger/bevel#1523]
**Is your feature request related to a problem? Please describe.**
Fabric Private Chaincode is a new type of Fabric Chaincode which allows to execute smart contracts with the help of trusted execution environments (i.e., Intel SGX) to enhance protection of a smart contract and data.

Fabric Private Chaincode requires the use of external builders / chaincode-as-a-service feature in Fabric. Adding support for this may required to resolve issue #1284 first.

**Comment by suvajit-sarkar** [comment]
Stale issue, closing it
