### ISSUE TITLE
feat(fabric): ansible decoupling for create/channel_artificats role

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#1576]
### Description
As a developer, I want to decouple Ansible from BAF. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templatizing purposes only.

This issue covers the change needed for create/channel_artificats role

#### State of the deployment before running of the new role (subject to change, if required)
1. Channel artificats not generated
2. Genesis block not present in vault

#### State of the deployment after running the new role (subject to change, if required)
1. MSP folder to be fetched from the vault in the chart and channel artifacts created (along with anchor peer update) from the configtx stored in vault.
2. Channel artifacts and anchor peer artifacts stored in vault
3. Genesis block should be created and stored in vault

_**THE ABOVE THIRD POINT IS FROM ANOTHER ROLE create/genesis AND IS MOVED TO THIS ISSUE AS PER MINIMAL CHARTS LOGIC**_

### Acceptance Criteria
1. The create/channel_artificats role should be modified in such a way that ansible is only used for templatizing purpose.
2. The previous and expected state of the deployment shall match the above description

**Comment by mgCepeda** [comment]
I will take this issue

**Comment by sownak** [comment]
Channel Artifacts creation require that MSP details of all the parties of the channel be present at the same location. Also, creating the Genesis file will need all MSP details. Hence, we cannot do this via a Helm Chart as that would mean sharing MSP details with one party in the consensus. The Genesis and channel artifacts creation will be done via Ansible (in the ansible controller) for Fabric, and all other networks like Besu/Quorum as well.
