### ISSUE TITLE
Consistent way of creating PVs

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/bevel#1717]
**Describe the bug**
Cloud platforms have their own way of handling the PV creation. Kubernetes does define an interface but everybody is free to implement their own volume creation strategy. The inconsistency in the way volumes are requested fails the deployment. Some part of this problem can also be attributed to pod scheduler design at the Kubernetes.

For example, in case of Hyperledger Fabric, the Peer node uses `kind: PersistentVolumeClaim` but the Orderer node uses `volumeClaimTemplates`. The cluster behavior is unpredictable and hard to optimize through `StorageClass` settings.

**To Reproduce**
1. Repeatedly install/uninstall Hyperledger Fabric on low resource availability K8s cluster.

**Expected behavior**
No issue at the Kubernetes scheduler, specially not because of the way PVCs are expected to be created.

**Screenshots**
NA

**Environment (please complete the following information):**
 - K8s: AKS, GCP etc
 - Version: 1.19+

**Additional context**
It would be nice to stick to `volumeClaimTemplates` for volume creation, the cloud platform dependencies (if any) can be largely mitigated with one approach.
Attaching the [conversation link](https://chat.hyperledger.org/channel/blockchain-automation-framework?msg=mPB8XopEZbrKERsML) for reference.

**Comment by suvajit-sarkar** [comment]
the volumeClaimTemplates can be used for StatefulSet, and in this case the only change would be on peernode chart

**Comment by arsulegai** [comment]
> the volumeClaimTemplates can be used for StatefulSet, and in this case the only change would be on peernode chart

Sure, another way to solve for other kind deployments is to keep them stateless or avoid any specific PV dependency. i.e. Use external databases/data sources where possible, use memory mounted volumes for ephemeral storage during the container life etc.
