### ISSUE TITLE
feat(fabric): ansible decoupling for chaincode ops

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#1720]
### Description
As a developer, I want to decouple Ansible from BAF. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templatizing purposes only.

This issue covers the change needed for chaincode-ops related roles

#### State of the deployment before running of the new role (subject to change, if required)
1. git_password absent in the vault/not stored as secret
2. organization certificates absent in the vault

#### State of the deployment after running the new role (subject to change, if required)
1. git_password present in vault/stored as secret
2. organization certificates present in vault

The following ansible tasks need to be moved for this to happen
[TASK-1](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/88a876a2f135c7d2180f1653a20f49d994cb3fa7/platforms/hyperledger-fabric/configuration/roles/create/chaincode/install/tasks/valuefile.yaml#L31)  
[TASK-2](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/88a876a2f135c7d2180f1653a20f49d994cb3fa7/platforms/hyperledger-fabric/configuration/roles/create/chaincode/commit/tasks/write.yaml#L3)  
[TASK-3](https://github.com/hyperledger-labs/blockchain-automation-framework/blob/88a876a2f135c7d2180f1653a20f49d994cb3fa7/platforms/hyperledger-fabric/configuration/roles/create/chaincode/invoke/tasks/write.yaml#L3)  

### Acceptance Criteria
1. The corresponding roles should be modified in such a way that ansible is only used for templatizing purpose.
2. The previous and expected state of the deployment shall match the above description

**Comment by mgCepeda** [comment]
I'll take this issue
