### ISSUE TITLE
Spike: Integrating support for private transactions in Express App

### ISSUE THREAD

**Issue by kaverikhaneja** [hyperledger/bevel#1747]
### Description
As a developer I want the express app developed in issue #1562  to communicate with the deployed smart contract in a HL-Besu network and be able to do private transactions via the endpoints exposed with this express application.

### Proposed Solution
Follow the documentation [Interact with private contracts](https://besu.hyperledger.org/en/stable/Tutorials/Contracts/Calling-Contract-Functions/#2-perform-a-write-operation_1) to modify the existing express code.

### Acceptance Criteria
If deploying the supply-chain smart contract:

1. Register some products in the network via the endpoint exposed for that in particular.
2. Get the products via the express API and check if they were registered correctly in the blockchain.

**Comment by vishaalreddy** [comment]
Please assign it to me.

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
@suvajit-sarkar @jagpreetsinghsasan 
For this issue, a private transaction has been managed manually. To carry out said transaction, the following process has been followed.
First, following, the abi and bin files have been created using the comple.js and SimpleStorage.sol files from the documentation.
https://besu.hyperledger.org/en/stable/private-networks/tutorials/contracts/#use-eth_sendsignedtransaction.
Then we proceed to execute the node private_tx.js. I attach the necessary files here. (Change the extension to .js)
[private_tx.txt](https://github.com/hyperledger/bevel/files/10533940/private_tx.txt)
[keys.txt](https://github.com/hyperledger/bevel/files/10534072/keys.txt)
The directory structure that you must have to execute the contract is the following:
<img width="176" alt="image" src="https://user-images.githubusercontent.com/83813093/215433226-be460ff9-e7fe-4c75-b48b-ff07be31e23e.png">
It has been done successfully for the IBFT and QBFT consensus with version 21.10.6 and for the QBFT consensus version 22.10.2
Besu-IBFT-21.10.6
<img width="545" alt="image" src="https://user-images.githubusercontent.com/83813093/215433919-2437f1bd-31b6-46dd-8a01-e9642689e575.png">
Besu-QBFT-21.10.6 
<img width="503" alt="image" src="https://user-images.githubusercontent.com/83813093/215434046-af94ab0e-5820-4bc1-8c33-dbe2b8813dc6.png">
Besu-QBFT-22.10.2
<img width="536" alt="image" src="https://user-images.githubusercontent.com/83813093/215434151-33e241be-9d07-4ecc-83df-cd13b1c76241.png">
And the setup for the tests carried out has been the following:
<img width="507" alt="image" src="https://user-images.githubusercontent.com/83813093/215434483-daa23971-d99b-4f1d-855a-8a15ef177400.png">
