### ISSUE TITLE
Referenced path does not exist

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/bevel#1749]
The referenced path in this line is not present in the vault. A similar path is added but only for `/users`. The role `chaincode` -> `commit` has a task that is supposed to copy this information.

https://github.com/hyperledger-labs/blockchain-automation-framework/blob/aa593062e7fb2e9c95a22fb4596785db01c8e91f/platforms/hyperledger-fabric/charts/commit_chaincode/templates/commit_chaincode.yaml#L204

**Comment by TonyRowntree** [comment]
I am taking this - 2

**Comment by TonyRowntree** [comment]
https://jira.hyperledger.org/browse/FAB-16986

**Comment by TonyRowntree** [comment]
@arsulegai after investigating, the role write.yaml for chaincode -> commit simply puts the certificates into the vault at the following path `vault kv put {{ vault.secret_path | default('secretsv2') }}/crypto/peerOrganizations/{{ namespace }}/endorsers/{{ organization.name }}/users/admin/msp`. After manually checking the vault path I can confirm the certificates are placed in said path. 

Could you please clarify more on what you mean?

**Comment by TonyRowntree** [comment]
@arsulegai Have you had a chance to check this? We have checked that the endorsers certificate are copied correctly to the vault and read correctly in commit_chaincode chart.

**Comment by sownak** [comment]
Closed because of idle and no change needed.
