### ISSUE TITLE
Ensure successful storage of cryto materials in vault by Corda Enterprise helm charts

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1759]
### Description
As a developer I want to check and ensure that the store certs are successfully storing the cryto materials in vault.

### Acceptance Criteria
1. Checks to ensure cryto successfully stored
2. Retry logic based on the above check
3. Add retry logic for reading from vault

**Comment by surabhi-dudhediya** [comment]
I will work on this issue

**Comment by TonyRowntree** [comment]
@surabhi-dudhediya is it ok to take this issue?

**Comment by surabhi-dudhediya** [comment]
> @surabhi-dudhediya is it ok to take this issue?

@TonyRowntree yes you can work on this issue
