### ISSUE TITLE
Use ghcr.io instead of docker hub to store and release the docker images

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#1780]
### Description
As a developer I want to store Bevel images at ghcr.io/hyperledger/bevel-<suffix> so that I can integrate using Github Actions and remove dependency on Docker Hub

Update the build images github actions workflow  at .github/workflows/docker_build.yml

### Acceptance Criteria
1. baf-build Images/packages available on gchr.io
2. corda os images available on ghcr.io

**Comment by bhuwanupadhyay** [comment]
I am interested to contribute to this.

**Comment by surabhi-dudhediya** [comment]
I would like to work on this issue

**Comment by TonyRowntree** [comment]
Spoke with @surabhi-dudhediya and I am taking this now

**Comment by TonyRowntree** [comment]
![image](https://user-images.githubusercontent.com/33454202/148255497-e2621d78-70e5-42f7-84fe-15c0682d945c.png)

by default when you fork a repo the permission for the github token is read only, the permissions can be elevated by a user with admin rights. It could be possible to not require elevated rights if the user that merges the PR has admin rights to the repo but that is something that we would need to test. Additionally, admins can set permissions for the githubToken on a job basis meaning that only the jobs that need elevated permissions can be granted them

Source for info: https://docs.github.com/en/actions/security-guides/automatic-token-authentication

**Comment by TonyRowntree** [comment]
Based on the above, when I tried to test the feature on my fork I received an authorization error seen below.

![image](https://user-images.githubusercontent.com/33454202/148256398-db33ff2f-d939-451f-96e6-53c1158c2256.png)

**Comment by TonyRowntree** [comment]
Turns out the above is an issue with how the tags work when pushing to ghcr - I have managed to push the packages to my personal fork. Updating the commit with the working code.

**Comment by TonyRowntree** [comment]
Updated commit - ready for review
