### ISSUE TITLE
Ansible Inventory for AWS EKS

### ISSUE THREAD

**Issue by saikumar-neelam** [hyperledger/bevel#1782]
**How to change the ansible provisioner file for AWS EKS cluster**
I am working on AWS and need to deploy the Hyperledger Fabric on AWS EKS Cluster. As i am new to ansible, it is bit difficult to understand about the provisioner files. Here in the code localhost is configured in ansible_provisioner. It would be really great if you can provide the samples of ansible provisioner for AWS EKS /Azure AKS Clusters.

**Comment by jagpreetsinghsasan** [comment]
@saikumar-neelam thanks for using Hyperledger Bevel.
We have used ansible to automate creation of value files for the helm charts, pushing them to the git repository and doing some configurations.
So in that case, we can run ansible over an instance/container/pod with both host and the controller being the localhost itself.
The deployments in the EKS cluster occur via flux (gitops) (except for the flux itself, which gets deployed by a shell command executed by ansible controller)

**Comment by jagpreetsinghsasan** [comment]
@saikumar-neelam  does this answer your question? (If yes, we can close this issue)

**Comment by saikumar-neelam** [comment]
@jagpreetsinghsasan : Thank you for response.
