### ISSUE TITLE
Missing file network-minikube.yaml 

### ISSUE THREAD

**Issue by pavanyadavalli** [hyperledger/bevel#1790]
As per the documentation:
https://blockchain-automation-framework.readthedocs.io/en/develop/developer/bevel_minikube_setup.html for hyperledger-Fabric, need to use network-minikube.yaml . But didnt find this file in the repository. Is the file name changed, if so please provide which file need to be used for setting Bevel on minikube.

**Comment by pavanyadavalli** [comment]
additional Information for file path :platforms/hyperledger-fabric/configuration/samples/network-minikube.yaml

**Comment by jagpreetsinghsasan** [comment]
Thanks @pavanyadavalli for pointing this out. The minikube based setup support is dropped from Bevel in the recent versions. The necessary cleanup missed out on the documentation. 
You can also create a PR for the necessary cleanup, if you are upto it :)
