### ISSUE TITLE
Update corda-ent documention to include cenm-console integration and operational guide

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1794]
### Description
As a developer I want to create the `cenm-console` operational guide and keep the Bevel corda-ent platform  documentation updated to the latest changes 

### Acceptance Criteria
1. Docs: cenm-console operational guide
2. Docs: update the configuration file section
3. Docs: vault paths, architecture reference

**Comment by nikhilayadav** [comment]
I will work on this issue

**Comment by surabhi-dudhediya** [comment]
I will work on this issue
