### ISSUE TITLE
Test automated deployment of latest fabric go chaincode

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1797]
### Description
As a developer I want to test the automated installation  of latest fabric go chaincode using Bevel

https://github.com/hyperledger/fabric-samples/tree/main/asset-transfer-basic

### Acceptance Criteria
1. Automated deployment of network with the chaincode lifecyle done
2. Automation works for both latest fabric samples chaincode and existing Bevel supplychain chaincode

**Comment by mgCepeda** [comment]
I'will take this issue
