### ISSUE TITLE
Add supplychain image build in Git Actions

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1823]
### Description
As a developer I want to build and push the following images for a specific tag to ghcr.io.

Images -
1. supplychain corda
2. supplychain fabric
3. supplychain front end
4. alpine-utils
5. h2 images

### Acceptance Criteria
1. Git workflow for auto build and push to ghcr.io
2. Update sample network yamls and tpl files to point docker registry to ghcr.io

**Comment by mgCepeda** [comment]
I,ll take this issue

**Comment by sownak** [comment]
alpine-utils and h2 I will push, no need to code that in.
