### ISSUE TITLE
feat(quorum): ansible decoupling raft crypto creation

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#1835]
### Description
As a developer, I want to decouple Ansible from BAF. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templating purposes only.

This issue covers the change needed for create/crypto/raft related role.

#### State of the deployment before running of the new role
1. Raft related crypto like nodekey, keystore absent in Vault

#### State of the deployment after running the new role
1. Raft related crypto like nodekey, keystore absent in Vault

The following tasks need to be completed for this to happen:

- Create a new Job Chart similar to `platforms/quorum/charts/crypto_ibft` called `cryto_raft`
- The above Job should do what `platforms/quorum/configuration/roles/create/crypto/raft` role does currently.
- Update the `platforms/quorum/configuration/roles/create/crypto/raft` role to only create the helmrelease file similar to `platforms/quorum/configuration/roles/create/crypto/ibft` role
- Remove the meta from both roles above as they are not needed.

### Acceptance Criteria

1. The previous and expected state of the deployment shall match the above description
2. Quorum network using Raft consensus must be successfully deployed.

**Comment by manikanta-darsi** [comment]
please assign it to me.
