### ISSUE TITLE
feat(quorum): Ansible decoupling of create/certificates/ambassador role

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#1854]
### Description
As a developer, I want to decouple Ansible from Bevel. This is achieved by moving the extra functionality from ansible to helm charts and use ansible only for templating purposes only.

This issue covers the change needed for `platforms/quorum/configuration/roles/create/certificates/ambassador` role. 

#### State of the deployment before running of the new role (subject to change, if required)
1. Root certificates not created
2. TLS certs not created
3. Root certs not on Vault
4. TLS certs not on Vault
5. Ambassador secrets not present on Kubernetes

#### State of the deployment after running the new role (subject to change, if required)
1. Root certificates created and saved to Vault
2. TLS certs created and saved to Vault
3. Ambassador secrets set as kubernetes secrets

### Acceptance Criteria
1. The create/certificates/ambassador role should be modified in such a way that ansible is only used for templating purpose.
2. The previous and expected state of the deployment shall match the above description

**Comment by manikanta-darsi** [comment]
please assign it to me
