### ISSUE TITLE
feat(fabric): modify operations code to incorporate orderer(s) and peer(s) in each organization

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#1874]
### Description
This issue has the same description as that of #1873, just meant to repeat the same process for operations tasks mentioned [here](https://hyperledger-bevel.readthedocs.io/en/latest/operationalguide.html#fabric-operations)

### Acceptance Criteria
1. The network shall come up with the modified network.yaml along with testing of `ALL` operations tasks present [here](https://hyperledger-bevel.readthedocs.io/en/latest/operationalguide.html#fabric-operations)
2. One CA tools deployment per organization

**Comment by mgCepeda** [comment]
I'm doing tests on this issue

**Comment by mgCepeda** [comment]
Currently add-new-organization, add-peer and add-orderer operations have been tested

**Comment by suvajit-sarkar** [comment]
the code was committed on mixed-organization branch

**Comment by suvajit-sarkar** [comment]
closing this issue, a working code is created on the features/mixed-organization branch
