### ISSUE TITLE
Fail the pod when init container fails due to Vault access issues/missing credential

### ISSUE THREAD

**Issue by arsulegai** [hyperledger/bevel#1922]
**Is your feature request related to a problem? Please describe.**
At present, the error if any during the read operation and the authentication is ignored. This will send a wrong signal to the Kubernetes engine. Where it continues to run the container but without the expected secrets loaded into appropriate folders. The whole experience leads to a bad state of the deployment.

**Describe the solution you'd like**
Fail the init container if load from Vault fails for any of the reasons including authentication, authorization of the service account token, missing secrets etc.

**Describe alternatives you've considered**
To manually fail the pod and monitor them for such errors.

**Additional context**
NA

**Comment by suvajit-sarkar** [comment]
Hi @arsulegai, we believe that its fixed, can you confirm which charts still have this issue?

**Comment by arsulegai** [comment]
@suvajit-sarkar there are cases when `curl` returns status as `0` even though the HTTP response is not 200. These are the cases where the init container is assumed to be working fine and the pod gets stuck forever. For example, the check here avoids the init container from exiting with code 1 https://github.com/hyperledger/bevel/blob/fcc190d5903061c0cb39790319670c370fd02c75/platforms/hyperledger-fabric/charts/peernode/templates/deployment.yaml#L83.

A stackoverflow question on one such case https://superuser.com/questions/590099/can-i-make-curl-fail-with-an-exitcode-different-than-0-if-the-http-status-code-i

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by arsulegai** [comment]
Thank you @mgCepeda for the PR.
