### ISSUE TITLE
helm lint: Destination directory ./build/test does not exist

### ISSUE THREAD

**Issue by uqix** [hyperledger/bevel#1930]
https://github.com/hyperledger/bevel/blob/bbdf9312c34a9ffece7cadf9480be1de7849f056/platforms/shared/configuration/roles/helm_lint/tasks/main.yaml#L37

I needed to remove `local_action` to make it work, FYI, my ansible controller and the managed node are the same one:

<img width="823" alt="image" src="https://user-images.githubusercontent.com/10142314/165090701-fd999dce-ba19-4474-b612-b1ecd2f9f8f2.png">

**Comment by suvajit-sarkar** [comment]
@uqix can you kindly confirm the ansible version you are using.

**Comment by uqix** [comment]
```
ansible [core 2.12.3]
  config file = None
  configured module search path = ['/home/kulu/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/kulu/.local/lib/python3.8/site-packages/ansible
  ansible collection location = /home/kulu/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/kulu/.local/bin/ansible
  python version = 3.8.11 (default, Sep  1 2021, 12:33:46) [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)]
  jinja version = 3.1.1
  libyaml = True
```

**Comment by suvajit-sarkar** [comment]
Unable to reproduce the bug using the LTS versions of Ansible and other related tools.
