### ISSUE TITLE
Adding a new organization in Hyperledger Fabric operation fails

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1932]
**Describe the bug**
Adding a new organization in Hyperledger Fabric operation using the operational [guide](https://hyperledger-bevel.readthedocs.io/en/latest/operations/adding_new_org_fabric.html) fails

**To Reproduce**
1. Setup fabric network using bevel
2. Follow the adding org operation guide 
4. See error in the ansible output

**Expected behavior**
The automation should complete without error and the new org is added to the network

**Additional context**
Missing role:
https://github.com/hyperledger/bevel/blob/bbdf9312c34a9ffece7cadf9480be1de7849f056/platforms/hyperledger-fabric/configuration/add-organization.yaml#L125

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
I'll take this issue
