### ISSUE TITLE
HLF deployment on azure aks cluster

### ISSUE THREAD

**Issue by amitkd-github** [hyperledger/bevel#1941]
I have tried to deploy the HLF on azure AKS, but i can see there aws dependencies. the scripts has been provided only for aws.

can any one help me to implement the same on azure AKS cluster.

Appreciate for the prompt response.

Thanks,
Amit

**Comment by uqix** [comment]
Tips about adding cloud_provider for private k8s posted here: https://github.com/hyperledger/bevel/issues/1001#issuecomment-1125908098

**Comment by suvajit-sarkar** [comment]
Hi @amitkd-github, which scripts are you referring to?

**Comment by suvajit-sarkar** [comment]
Closing this issue as it is stale.
