### ISSUE TITLE
Hashicorp Vault secrets versions for the Supplychain example

### ISSUE THREAD

**Issue by joseucarvajal** [hyperledger/bevel#1946]
**Describe the bug**
I'm trying to set up the Supplychain example and I'm currently facing an issue regarding the Vault Secrets engine version.

Hashicorp secret engine versions for Supplychain network and REST API is different.
For network set up: secrets V2 engine
For REST API set up: secrets V1 engine

This difference lead us to an error, since we've created the network with secrets v2 (vault kv get) and the API is trying to reach a secrets v1 (curl) then the API setup fails.

**To Reproduce**
1. Set up a network (platforms/shared/configuration/site.yaml) with a vault secrets v2 engine
2. Run the deploy the supply chain app (examples/supplychain-app/configuration/deploy-supplychain-app.yaml)
3. The deploy supply chain app will fail trying to access a secrets V2 engine

**Expected behavior**
API runs successfully

**Environment (please complete the following information):**
 - OS: MacOS
 - Version Monterrey 12.3.1

**Additional context**
The network has been set up successfully in the GCP cloud provider

**Comment by joseucarvajal** [comment]
Figured out what was going on. Just needed to change the bevel/examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl.

**Comment by sownak** [comment]
@joseucarvajal Would you be willing to submit a PR for this fix?

**Comment by joseucarvajal** [comment]
@sownak it's not necessary to submit a PR. It has to do more with the documentation, If someone ever faces this issue, just update the username and secrets path in the file: bevel/examples/supplychain-app/configuration/roles/helm_component/templates/restserver.tpl.

<img width="998" alt="image" src="https://user-images.githubusercontent.com/5514431/168593464-f086aee8-a5bb-41df-a246-ecb9956a20f1.png">
