### ISSUE TITLE
charts/catools/certs/orderer1-ca.crt written by staging release is overwritten by prod release later

### ISSUE THREAD

**Issue by uqix** [hyperledger/bevel#1947]
**Describe the bug**

`platforms/hyperledger-fabric/charts/catools/certs/orderer1-ca.crt` written by staging release is overwritten by prod release later.

**To Reproduce**
1. deploy network into platforms/hyperledger-fabric/releases/staging
2. deploy network into platforms/hyperledger-fabric/releases/prod
3. see: staging `platforms/hyperledger-fabric/charts/catools/certs/orderer1-ca.crt` overwritten by prod

**Expected behavior**

One crt per release, i.e.

* platforms/hyperledger-fabric/charts/catools/certs/`staging-`orderer1-ca.crt
* platforms/hyperledger-fabric/charts/catools/certs/`prod-`orderer1-ca.crt

**Comment by sownak** [comment]
@uqix That is most likely because you have specified the same path in network.yaml. Bevel does not create the certs in `platforms/hyperledger-fabric/charts/catools/certs`

**Comment by uqix** [comment]
https://github.com/hyperledger/bevel/blob/fcc190d5903061c0cb39790319670c370fd02c75/platforms/hyperledger-fabric/configuration/roles/create/ca-tools/peer/tasks/main.yaml#L69-L74

**Comment by sownak** [comment]
@uqix Thanks. That does look like a bug. Needs to be fixed properly.
