### ISSUE TITLE
feat(shared): dci lint tool github action

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#1949]
### Description
As a developer, I want to create a github action which gets triggered for every PR to develop & main, so that the project code follows the inclusive language statements

[Here](https://github.com/petermetz/gh-action-dci-lint#usage) is the github action for reference

### Acceptance Criteria
1. The github action should be setup and shall work on all PR's

**Comment by DeavyGaut** [comment]
Hi @suvajit-sarkar, let me have a look at this issue.

**Comment by suvajit-sarkar** [comment]
@DeavyGaut any update on this issue?
