### ISSUE TITLE
Update fabric sample configuration files

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1950]
### Description
As a developer I want to update the fabric sample configuration for the major operations and remove deprecated ones. 

### Acceptance Criteria
1. Update/Add Samples of major operations
2. Remove deprecated samples

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by jagpreetsinghsasan** [comment]
We need to update the corresponding references for the same, in our documentation as well, as all of the code snippets from network.yaml file present in the documentation are direct references from these sample network.yaml files.

**Comment by jagpreetsinghsasan** [comment]
https://hyperledger-bevel.readthedocs.io/en/latest/operations/fabric_networkyaml.html
