### ISSUE TITLE
feat(corda): update platform r3 corda os helm value templates for flux v2

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#1971]
### Description
As a developer I want to use flux v2 as gitOps for the network deployment. 

Spike story: https://github.com/hyperledger/bevel/issues/1283
Reference Setup: https://fluxcd.io/docs/installation/

### Acceptance Criteria
1. network deployed and verified with application

**Comment by mgCepeda** [comment]
I'll take this issue
