### ISSUE TITLE
feat(fabric): vault path structure modification

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2017]
### Description
Current Bevel certificate paths on vault for fabric platform has separate paths for orderer and peers, which makes sense as Orderer and peers were separated organization. But with the feature/mixed-organization, an organization can now host both orderers and peers. Current path structure can be found [here](url)

As developer, I want to merge the vault crypto paths for orderers and peers belonging to same organization and have it under single crypto/organisation path

### Acceptance Criteria
1. Suggest the new path changes
2. Make code changes to store and use crypto's from the new paths

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
Currently add-new-organization, add-peer and ad-orderer operations have been tested
