### ISSUE TITLE
fix(fabric): orderer org input is not a list

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2038]
**Describe the bug**
In our network.yaml, under the `network.channels[*].orderer.name` is a key value pair. This should be changed to a list to support multi orderer organizations at the start itself (to facilitate #1874 )
Because this field is used while generating the configtx.yaml file which will generate incorrect profile configurations.  

For reference, check the loop of the profile configuration [here](https://github.com/hyperledger/bevel/blob/35e1223953f4298304036cc480cbc418d3ae1aa8/platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxProfile_default.tpl#L2) and then check the variable mentioned [here](https://github.com/hyperledger/bevel/blob/35e1223953f4298304036cc480cbc418d3ae1aa8/platforms/hyperledger-fabric/configuration/roles/create/configtx/templates/configtxProfile_default.tpl#L24). At line 24, the expected output should be a list of orderer organizations but the current code will generate it as a single item list because of `network.channels[*].orderer.name` field not being a list.

**To Reproduce**
1. Deploy the network with multiple orderer organizations.
2. Verify the profile section in configtx.yaml for reference

**Expected behavior**
1. A correct configtx.yaml should be generated

**Comment by mgCepeda** [comment]
I'll take this issue
