### ISSUE TITLE
CrashLoopBackOff on flux pods while reseting other network on the same cluster

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2039]
**Describe the bug**
The flux pods goes into CrashLoopBackOff when reset playbook is run for any other network on the cluster

**To Reproduce**
1. Setup any two networks
2. Reset one of the networks
3. See CrashLoopBackOff  error on the other network flux pods

**Expected behavior**
The other network deployments should be unaffected by the reset

**Environment (please complete the following information):**
 - Version flux v2

**Additional context**
Seems to an issue with how flux v2 uninstall is done

**Comment by vishaalreddy** [comment]
I'll take this issue
