### ISSUE TITLE
Add QBFT consensus for bevel HL Besu platform

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2051]
### Description
As a developer, I want to include QBFT to the already existing consensus (IBFT, clique and ethash).
To do this, the developer can try the following steps in order

1. Understand and deploy the IBFT sample network mentioned [here](https://besu.hyperledger.org/en/stable/private-networks/tutorials/ibft/)
2. Understand the deploy the QBFT sample network mentioned [here](https://besu.hyperledger.org/en/stable/private-networks/tutorials/qbft/)
3. Understand the differences between the IBFT and QBFT network creation
4. Implement the necessary changes to enable QBFT

### Acceptance Criteria
1. The network.yaml should now support `network.config.consensus` as `qbft`
2. The network deployed should be running correctly (no error logs)
3. Necessary documentation to be updated

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
Hello. I have made the changes to be able to deploy besu with QBFT. But when looking at the logs of the nodes, a strange behavior was detected in Cmar were 3 peers in cmar and later 1 peer dropped and became 2 peers. And in the validator node 1 it says that there are 5 peers when there are only 3, 2 validators and 1 member.
<img width="672" alt="image" src="https://user-images.githubusercontent.com/83813093/206660600-e050d20d-65c2-4da5-a22d-0b1dd001faba.png">
<img width="667" alt="image" src="https://user-images.githubusercontent.com/83813093/206660776-4a6fdf53-0823-48d1-aff6-45d231cc10c2.png">

**Comment by mgCepeda** [comment]
The changes made can be found here
https://github.com/mgCepeda/blockchain-automation-framework/tree/feature-2051

**Comment by jagpreetsinghsasan** [comment]
@mgCepeda can you upgrade the binaries to 22.10.2 and try setting up the network again?
If it works, we can create one more issue for upgrade to 22.10.2 and then work on this QBFT

**Comment by adityajoshi12** [comment]
@mgCepeda are you also taking care of new node/org addition with QBFT consensus?

**Comment by mgCepeda** [comment]
> @mgCepeda are you also taking care of new node/org addition with QBFT consensus?

For this issue I have made the changes to the base code. I will make the changes for the operations in a separate issue
