### ISSUE TITLE
Besu - depending on external tools and artifacts

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2073]
**Describe the bug**
At various places in the initializations script, there are commands which are trying to download utility tools like `jq`, `curl` and `openssl`, also jar files on the run time using the wget commands. We shouldn't download the utilities/arefacts at runtime as systems may be in isolated zones. Also production systems shouldn't download may external dependencies  over the public internet.

**To Reproduce**
Inside the playbooks at may places we can find dependencies getting downloaded.
Example: 
1. https://github.com/hyperledger/bevel/blob/main/platforms/hyperledger-besu/charts/tessera_key_mgmt/templates/job.yaml#L54
2. https://github.com/hyperledger/bevel/blob/main/platforms/hyperledger-besu/charts/node_tessera/templates/deployment.yaml#L260

**Expected behavior**
There should be not such commands that are dependent on external dependencies. They can be the part of container image.

**Environment (please complete the following information):**
 - Besu network

**Comment by sownak** [comment]
@adityajoshi12 Thanks for raising this issue. Just to clarify, you are requesting that the Besu docker images should already contain the utilities like jq, curl etc.?

**Comment by adityajoshi12** [comment]
Yes, I am refering to besu, tessera and alpine-utils images (wherever there is need to downloading these binaries ).

**Comment by sownak** [comment]
As Bevel is not creating those images, it will be hard to maintain them. Anyone using Bevel for production should anyway maintain their own Besu/tessera and alpine-utils image and not use the images available on ghcr or dockerhub

**Comment by adityajoshi12** [comment]
Its not just about the maintaining the docker images but, the scripts also needed to be updated, so that they don't run the `apk add` or `wget` commands

**Comment by sownak** [comment]
yes, so you can add those conditions in the helm charts

**Comment by adityajoshi12** [comment]
can there be checks added in the helm charts, so that it doesn't pull the binaries?

**Comment by jagpreetsinghsasan** [comment]
Hi @adityajoshi12 I can suggest a solution here! :smile: 
For the `example 1`, one can modularize the helm chart.
Currently, that container fetches the custom vault token by requesting it to the vault (via the service account token).
And then the tessera library is using that token.

So, what one can do in this regard is,
Run an init container which fetches this token and mounts it as a volume (This init container can have jq, curl like utilities)
The main container then mounts this in-memory mount which holds the vault token and use it.
In this way, there will be no need of creating images with such binaries (jq, curl etc.) and base images of tessera etc etc.

**Comment by adityajoshi12** [comment]
This approach sounds good to me, this also needs to be done for the openssl certificates generation flows.

**Comment by jagpreetsinghsasan** [comment]
> This also needs to be done for the openssl certificates generation flows. Also need to be sure that utilities are not downloaded at runtime.

Yes, as soon as you containerise the binaries (make sure to not pollute the original container images provided by the platform like besu itself), this objective will get completed.
