### ISSUE TITLE
feat(quorum): update the lock var description

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2086]
**Describe the bug**
The `lock` variable is mentioned in places in the code including the network.yamls, but the description of the variable is not good enough, for example [here](https://github.com/hyperledger/bevel/blob/8827ecc2312c497cad355b3dfb5ea5429c4b9bbf/platforms/quorum/configuration/samples/network-quorum.yaml#L209)

**Expected behavior**
Existing description: `true or false: Sets Quorum node to lock or unlock mode`
Expected description: `true or false: corresponds to, **geth --allow-insecure-unlock**,  while starting up the node`

**Comment by mgCepeda** [comment]
I'll take this issue
