### ISSUE TITLE
[Besu] Duplicate generation of private, public keys even if they are present in vault

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2090]
**Describe the bug**
Currently the `create/crypto` playbook generates the public private key and node address for all nodes, even if their keys are present in the vault. And this happens when we again run the playbook, also this leads to generation of new genesis file will all the new address, even for the older nodes.

**To Reproduce**
Run the network more than once.

**Expected behavior**
Before generating the public private key and node address, playbook, should check for the keys in the vault and generate only for the new nodes.

**Environment (please complete the following information):**
 - Besu

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by adityajoshi12** [comment]
Hi @mgCepeda , I tried to address this issue in [PR](https://github.com/hyperledger/bevel/pull/2098), maybe you can do a validation check and take a call according.

**Comment by vishaalreddy** [comment]
I'll do validation check

**Comment by vishaalreddy** [comment]
I have done validation check and the code is working fine.
