### ISSUE TITLE
feat(shared): update security context in helm charts

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2103]
**Is your feature request related to a problem? Please describe.**
As a developer, I want to improve the current state of helm charts and thus want to add relevant security contexts to them.

**Describe the solution you'd like**
These are the various features which we can implement in our charts

- Security context of a pod
- Volume permissions
- Security context of container

Reference: `https://kubernetes.io/docs/tasks/configure-pod-container/security-context/`

**Describe alternatives you've considered**
Not basically an alternative, but we can have an extension to this by having the user, pre-defined in container images (not the ones which we use directly from the respective blockchain platforms) and then controlling that user from the k8s security context.

**Comment by maheshkasabe** [comment]
are we going to add this security contexts for only example apps ? just like supplychain-app & identity-app or for the whole bevel repository ??

**Comment by sailajakommineni** [comment]
i will look into this.
