### ISSUE TITLE
bug(shared): kind not working on github actions workflow runner

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2125]
**Describe the bug**
Molecule test stages are failing for pull requests

**To Reproduce**
1. Create a PR with platform tag
2. Let the Test Ansible using Molecule workflow run
3. Check the error in workflow logs

**Expected behavior**
The workflow should pass, or we should consider skipping the molecule test

**Screenshots**
![image](https://user-images.githubusercontent.com/55580532/212622776-47fef60e-d6a0-40ed-98ea-5efc546cac6c.png)

**Additional context**
[Error workflow](https://github.com/hyperledger/bevel/actions/runs/3922212084)

**Comment by saurabhkumarkardam** [comment]
I will check this.
