### ISSUE TITLE
docs: update vault paths for HL Besu and Quorum

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2126]
**Describe the bug**
The current [HL Bevel ReadTheDocs](https://hyperledger-bevel.readthedocs.io/en/latest/) has incorrect certificate path lists for Hyperledger Besu and Quorum platforms.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to [quorum certificate paths](https://hyperledger-bevel.readthedocs.io/en/latest/architectureref/certificates_path_list_quorum.html)
2. Verify the paths (some are incorrect/missing)
3. Go to [besu certificate paths](https://hyperledger-bevel.readthedocs.io/en/latest/architectureref/certificates_path_list_besu.html)
4. Verify the paths (some are incorrect/missing)

**Expected behaviour**
Correct and every certificate path should be mentioned

**Additional context**
To fix this, the easiest way is to deploy a quorum network with Bevel, expose vault UI and access the vault via UI, check paths, add and correct the existing paths in docs. (Similarly for HL Besu)

**Comment by vishaalreddy** [comment]
I'll take this issue
