### ISSUE TITLE
chore: rename shared roles

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2129]
### Description
As a developer, I want to cleanup and organize the code structure.
One of incorrect things are the shared roles [here](https://github.com/hyperledger/bevel/tree/main/platforms/shared/configuration/roles/create)
We should rename these roles from `shared_role-name` to just `role-name`

### Acceptance Criteria
1. Changing of `role-name` and their documentation references
2. Using the newly updated role names in the rest of the code, tested.

**Comment by maheshkasabe** [comment]
#2201
