### ISSUE TITLE
chore: update gh workflow names

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2130]
### Description
As a developer, I want to organize the workflows with the intended name based sorting.
The current names of the github workflow files are not organized, and we should change them like

- [x] chaincode_test.yml   ->   test_smartcontract.yml

- [x] corDapps_jar_build.yaml   ->   jar_cordapps.yml

- [x] corda_images_build.yml   ->   img_platform_corda.yml

- [x] corda_supplychain_images_build.yml   ->   img_suppychain_corda.yml

- [x] docker_build.yml  ->   img_bevel.yml

- [x] fabric_images_build.yml   ->   img_platform_fabric.yml

- [x] indy_image_build.yaml   ->   img_platform_indy.yml

- [x] molecule_test.yml   ->   test_molecule.yml

- [x] networkschema_test.yml   ->   test_networkschema.yml

- [x] quorum_images_build.yml   ->   img_platform_quourm.yml

- [x] supplychain_frontend_build.yml  ->   img_supplychain_frontend.yml

Currently it looks like:
![image](https://user-images.githubusercontent.com/56861721/213986513-543e6469-0e6e-49da-885b-5f1cbec4ffca.png)

After, sorted list on gh will look very organized like:
![image](https://user-images.githubusercontent.com/56861721/213985903-0fd3c377-a5f4-4d66-9acb-4dc740998f6b.png)

(add more description and relevant links)

### Acceptance Criteria
1. Update of the above mentioned files
2. Changing of relevant docs and references, if any

**Comment by mgCepeda** [comment]
I'll work on this issue
