### ISSUE TITLE
docs: update contributing guide

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2131]
### Description
As a developer, I want to update the contributing guide with the following information
1. Update pull request process and add more details. Can take reference from [here](https://github.com/hyperledger/cactus/blob/main/CONTRIBUTING.md#create-local-branch)
2. Addition of commit lint workflow to streamline commit messages. Can take reference from [here](https://github.com/hyperledger/cactus/blob/main/.github/workflows/commitlint-pull-request.yml)

### Acceptance Criteria
1. Addition of commit lint workflow mandatory on all PR to dev and main branches
2. Updation of contributing guide.

**Comment by maheshkasabe** [comment]
I would like to work on this,
Assign this to me !

**Comment by jagpreetsinghsasan** [comment]
Please join our planning calls if you have any questions regarding this, or you can ask here/discord
