### ISSUE TITLE
feat(besu): add automation code to deploy supplychain smart contract 

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2139]
### Description
As a developer, I want to enable private transaction support
The result of the spike done in #1747 will enable the developer to add the code and do the automation for the same.

### Acceptance Criteria
1. Private transactions should happen from our postman collection suite for the supplychain example for QBFT
2. Any upgrades done should be documented
3. Add besu express_app workflow to build and push to ghcr

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by jagpreetsinghsasan** [comment]
For the variable in private transaction being the `privateFor`, we need to either re-structure the entire supplychain application (as the privateFor will include multiple tm public keys, based on the number of counterparties in the request body)

The alternate solution to this is, to deploy the smartcontract as public transaction, and do public transaction queries as usual.
For the scope of this story, the output can be simply a screenshot showcasing that the network can indeed do private transactions.

@suvajit-sarkar , is this fine?
