### ISSUE TITLE
bug(shared): pods crashes post Kubernetes cluster nodes are restarted

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2155]
**Describe the bug**
Vault auth on pods fails post Kubernetes cluster nodes restart, causing the pods to crash.

**To Reproduce**
1. Deploy any platform
2. Restart the Kubernetes cluster nodes
3. See error as pod crashes due to vault auth failure

**Expected behavior**
Pods to start up and as work as expected

**Environment :**
 - Kubernetes 1.21 +

**Additional context**
The issue is fixed for fabric platform, PR #2152 , Need to have similar fix for other platforms

**Comment by mgCepeda** [comment]
I'll take this issue

**Comment by mgCepeda** [comment]
PR created for this issue
https://github.com/hyperledger/bevel/pull/2218

**Comment by mgCepeda** [comment]
After the reboot of the nodes there is some error in the pods, you can solve it by executing kubectl delete pod <pod_name> -n <namespace>
