### ISSUE TITLE
bug(docs): broken links in developer guide

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#2159]
**Describe the bug**
In the [developer guide](https://hyperledger-bevel.readthedocs.io/en/latest/developer/docker-build.html), the `Pre-requisites` section has 2 broken links referring to `install` and `configure`.

**To Reproduce**
1. Go to the above mentioned developer guide
2. Click on `install` and `configure` under `Pre-requisites` section
3. Those will lead you to 404 error code pages

**Expected behavior**
The above mentioned scenario should be fixed with the updated links to the referenced documentation

**Screenshots**
![image](https://user-images.githubusercontent.com/56861721/220816556-043efaed-a0da-45a7-a3b9-80cda9a3e9fb.png)

![image](https://user-images.githubusercontent.com/56861721/220816480-8425bb22-c3f5-44ab-8737-b61ea1691764.png)

**Comment by Dhananjay-12** [comment]
Hi @jagpreetsinghsasan , the links are working.

**Comment by jagpreetsinghsasan** [comment]
Cool, thankyou for the confirmation. We fixed the links in the PR #2161 but forgot to update the status here.
Thankyou for the quick response!

Closing the issue.
