### ISSUE TITLE
feat(shared): move cleanup of network roles to shared roles

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2206]
### Description
As developer I want to have a single and consistent way to cleaning up bevel deployed networks.

Current code has tasks written for each platform to clean up their network resources. The tasks which are common for all platforms such as cleanup of flux, cleanup of k8s resources and cleanup of git releases should be move to shared folder. 

### Acceptance Criteria
1. Add playbook in shared role to delete/clean up network
2. Move all common tasks to shared roles

**Comment by sailajakommineni** [comment]
i will look into this.
