### ISSUE TITLE
join channel job is not starting- JOB IS NOT STARTING AUTOMATICALLY

### ISSUE THREAD

**Issue by aswath-edx** [hyperledger/bevel#2212]
when create hyperledger fabric network with "Allchannel" as channel name the join job is not starting. then i try to helm install using value the job is started. and the same issue facing when i try new network with custom name of channel name. 

![Screenshot from 2023-04-14 14-37-42](https://user-images.githubusercontent.com/121422505/232001944-7d195218-f717-41a4-ba3c-d843aa24a14e.png)

![Screenshot from 2023-04-14 14-38-30](https://user-images.githubusercontent.com/121422505/232001803-56e6abae-4482-465c-af22-3f908af29a54.png)

![Screenshot from 2023-04-14 14-40-22](https://user-images.githubusercontent.com/121422505/232000734-356a1751-751b-4e70-ac82-f8a1e6113a29.png)

**Comment by shubham-edx** [comment]
following.

**Comment by sownak** [comment]
Seems like you are not following the steps to create a bug. Anyway, I see that your master channel job is complete. What is the error then?

**Comment by aswath-edx** [comment]
@sownak find the issue. in job  there is a length issue. so we cant give large name for org name or channel

**Comment by aswath-edx** [comment]
@sownak in screenshot you can seen the job is started ,but it happen when i tried manually like "helm install cmd" so the thing is that when automation is not working because for the total length of job. i think the total length should be 53 character or something

**Comment by aswath-edx** [comment]
fixed issue

**Comment by sownak** [comment]
ok, so the issue is that Bevel does not warn about the naming conventions or limit the characters in the org and channel names.
