### ISSUE TITLE
bug(r3 corda): reset network doesn't clean all git release

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2220]
**Describe the bug**
Running Bevel r3 corda reset network, cleans up network but some few release files are not deleted from the release path 

**To Reproduce**
1. Deploy r3 corda platform
2. Rest the network using the same network yaml
3. Check the release folder
4. See release files not completely deleted

**Expected behavior**
The release folder should be competed deleted

**Environment (please complete the following information):**
 - Branch : Develop

**Additional context**
R3 Corda deployment creates few release which are not under the org name or orgname-orgnamespace folder. These releases are not getting deleted as the logic of cleanup of release folder has changed

**Comment by mgCepeda** [comment]
I'll take this issue
