### ISSUE TITLE
bevel-samples: update all the samples configuration files with correct repo and chart path

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2222]
### Description
As a developer I want to update the samples configuration files with correct repo and chart path in the new bevel-samples repository

### Acceptance Criteria
1. All sample configuration files in both bevel examples updated.

**Comment by sailajakommineni** [comment]
i will look into this.

**Comment by ravikiranjanjanam** [comment]
[ci-skip] updated repo and chart path #23 --> PR raised in bevel-samples repo
