### ISSUE TITLE
docs: issue in contributing page of bevel documentation

### ISSUE THREAD

**Issue by ayush4345** [hyperledger/bevel#2242]
**Describe the bug**
[contributing](https://hyperledger-bevel.readthedocs.io/en/latest/contributing.html) page of bevel documentation

It is a minor issue regarding the page formatting, as you can see in the green arrow.

**To Reproduce**

1. Scroll down to the green arrow
2. See the error that subpoints are not properly written

**Expected behavior**
the subpoints should be clearly differentiable

**Screenshots**
![image](https://github.com/hyperledger/bevel/assets/99096397/36b3a507-4932-4c79-a37b-fc7054b63808)

I am willing to work on this issue. Should I go ahead and fix it?

**Comment by YashPimple** [comment]
Hello @ayush4345 can I work on this issue?

**Comment by ayush4345** [comment]
> Hello @ayush4345 can I work on this issue?

Actually I am working on it

**Comment by rudrakshkarpe** [comment]
I guess, it's been quite a while since this issue is been pending. If no one is working on it. I would like to raise a PR.
