### ISSUE TITLE
bug(shared): test_molecule workflow reporting errors in the ansible roles

### ISSUE THREAD

**Issue by ravikiranjanjanam** [hyperledger/bevel#2249]
**Describe the bug**
test_molecule workflow reporting errors in the ansible roles

**To Reproduce**

Create a PR with platform tags or shared tag
Let the Test Ansible using Molecule workflow run
Check the error in workflow logs

**Expected behavior**
workflow should pass with no errors in the ansible roles

**Screenshots**
<img width="446" alt="image" src="https://github.com/hyperledger/bevel/assets/107536370/69317ec4-a638-4bfe-b4ad-99a2d80e6a6d">

**Comment by suvajit-sarkar** [comment]
Molecule test support is removed
