### ISSUE TITLE
feat(quorum): enable deployment of cacti connector for Quorum platform

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2253]
### Description
As a developer I want enable automation deployment of cacti connector on GoQuorum nodes.

Reference pull request: https://github.com/hyperledger/bevel/pull/2175

### Acceptance Criteria
1. Guide under quorum operations.
2. Test cacti API's

**Comment by saurabhkumarkardam** [comment]
I will check this.
