### ISSUE TITLE
spike(fabric): support for Hyperledger fabric v2.5.x

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2300]
### Description
As a developer I want to add platform support for Hyperledger fabric v2.5.x. This issue explores the changelogs, steps and code changes required to add support for upgrade.

### Acceptance Criteria
1. Document changes, steps for add support
2. Document steps to support running upgrade
3. Create issue to add support

**Comment by mgCepeda** [comment]
**New features**

- 2.3.0:
  - Hyperledger Fabric 2.3: introduced the ability to manage an ordering service without a system channel. 
  - It is now possible to take a snapshot of a peer’s channel information
- 2.4.0
  - Fabric Gateway is a new service running on peer nodes that manages trans-action submission and processing for client applications
  - You can now unjoin a peer from a channel when the channel is no longer needed. 
  - You can calculate the package ID from a packaged chaincode without installing the chaincode on peers using the new peer lifecycle chaincode calculatepackageid command.
- 2.5.0
  - While it has always been possible to delete private data from current state, this new feature enables purging the history of private data from a peer while preserving a hash of the private data as immutable evidence on the blockchain.
  - The release binaries and docker images have been updated

**Deprecations (existing) and changes**

- Ordering service system channel is deprecated. Without using the syschannel, changes may be necessary in the genesis and channel creations.
- Support for specifying orderer endpoints at the global level in channel configuration is deprecated. It will also be necessary to make changes to the configtx.yaml file.
- The 'Kafka' consensus type is deprecated, it is recommended to use Raft instead.
- Fabric CouchDB image is deprecated
- The fabric-tools docker image will not be published in future Fabric releases
- Version 1.4.8 is likely to stop working with the new changes

For more details on these points, see following document.
[feature-2300.pdf](https://github.com/hyperledger/bevel/files/12273535/feature-2300.pdf)
