### ISSUE TITLE
bug(besu): addition of the new org fails

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2316]
**Describe the bug**
Addition of the new org in the besu fails due to the missing genesis file.

**To Reproduce**
1. run the besu network once
2. remove the build directory
3. add a new org to the existing network

**Expected behavior**
Addition of the org should run the validators sucessfully.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by adityajoshi12** [comment]
The issue is at this place, where we try to get the genesis file from the vault, which doesn't exist at that moment.
https://github.com/hyperledger/bevel/blob/main/platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/validator_vote.yaml#L50C1-L61C1

**Comment by adityajoshi12** [comment]
Addition of new org also fails at https://github.com/hyperledger/bevel/blob/main/platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/nested_validator_vote.yaml#L28 , where we try to vote from the node. which is not up yet, i this this step can be removed.

**Comment by suvajit-sarkar** [comment]
> Addition of new org also fails at https://github.com/hyperledger/bevel/blob/main/platforms/hyperledger-besu/configuration/roles/create/validator_node/tasks/nested_validator_vote.yaml#L28 , where we try to vote from the node. which is not up yet, I think this step can be removed.

This seems to be working fine on my initial test. The voting needs to include new validators as voters once added
