### ISSUE TITLE
docs(shared): complete restructure and redesign of documentation

### ISSUE THREAD

**Issue by saurabhkumarkardam** [hyperledger/bevel#2325]
**Description:**
As part of enhancing the user and developer experience, we propose a complete restructure and redesign of the documentation for Hyperledger Bevel, will provide more precise and concise instructions on how to start with Hyperledger Bevel.

---

**Objective:**
The main goal of this task is to restructure and redesign the documentation so that both beginners and experienced developers can easily understand how to get started with Hyperledger Bevel. The new documentation work should cover prerequisites, installation steps, and a step-by-step guide to running a primary Bevel network.

---

**Addition context:**
The restructured documentation aims to improve user and developer experience by providing clearer instructions on getting started with Bevel.

**Comment by suvajit-sarkar** [comment]
closing as duplicate
