### ISSUE TITLE
feat(shared): spell and grammar linting

### ISSUE THREAD

**Issue by saurabhkumarkardam** [hyperledger/bevel#2327]
As a developer, I want to enforce the usage of proper commit messages in all Pull Requests (PRs) to maintain code quality and consistency. 

**Issue:**

currently, we lack a tool or feature to make sure that the PRs we receive for our project follow the correct PR format.

---

**Solution:**

To address this issue, we can implement `GitHub Spellcheck`, a tool that automatically checks the spelling and grammar in commit messages whenever a PR is created. By integrating this tool into our repository, we can ensure that all future PRs have correctly spelled and well-written commit messages.

---

**Additional context:**
GitHub Spellcheck will improve the quality of Hyperledger Bevel Pull Requests.

**Comment by sailajakommineni** [comment]
i am working on this.
