### ISSUE TITLE
feat(shared): molecule test support to be removed

### ISSUE THREAD

**Issue by saurabhkumarkardam** [hyperledger/bevel#2331]
As a developer, I want to remove Molecule testing support from the Hyperledger Bevel project.

**Issue:**

Currently, Molecule testing causes issues when creating pull requests (PRs) for all molecule testing-supported platforms.

---

**Solution:**

To address this problem, we will:

1. Remove the Molecule testing code from the Hyperledger Bevel project's GitHub workflow.
2. Delete the Molecule code directory from each platform directory (if the platform supports molecule testing).
3. Ensure that after performing the above two steps, there is no molecule testing when we create a new Pull Request.

---

**Additional context:**

This issue will remove the functionality of molecule testing from our project.

**Comment by suvajit-sarkar** [comment]
Create a story/issue for testing helm chart for each platform.

**Comment by saikumarbommakanti** [comment]
This task is done
