### ISSUE TITLE
feat(shared): replace ambassador with ambassador edge stack

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2359]
### Description
As a developer I want to start using the ambassador edge stack for all platforms expect fabric (will only support HAProxy)

- [x] besu
- [x] quorum
- [x] indy
- [x] R3 Corda os
- [x] R3 Corda ent
- [x] Substrate
- [x] Fabric (remove ambassador code)

### Acceptance Criteria
1. Network deployed and tested with ambassador edge stack

**Comment by sailajakommineni** [comment]
i am testing on r3corda os &ent.

**Comment by sownak** [comment]
I am taking up Quorum

**Comment by saikumarbommakanti** [comment]
I am working on r3cordaos

**Comment by saurabhkumarkardam** [comment]
I will check it for Substrate.
