### ISSUE TITLE
chaincode-ops does not upgrade smart contract as keep same sequence value (1)

### ISSUE THREAD

**Issue by icordoba** [hyperledger/bevel#2370]
**Describe the bug**
Running chaincode-ops just changing the chaincode version (i.e.: 1 -> 2) generates an invalid process as version is correctly passed (2) but sequence is kept with original value (1) so process fails in the approve step. (chaincode is correctly installed (first step).

**To Reproduce**
Deploy Java chaincode using a basic network.xml will do using version 1 as value
Update version from 1 to 2 (or any value. It should not make a difference)
Use chaincode-ops to upgrade the chaincode version
Review how Approve pod generated fails as sequence number is not updated. Approve pod deployed will fail. Perform kubectl logs to confirm the error related to sequence value.

**Expected behavior**
Sequence value should be increase by one when a chaincode upgrade is performed.

**Environment (please complete the following information):**
Hyperledger Fabric 2.2.2
AKS Kubernetes service
Java chaincode

**Comment by sownak** [comment]
Documentation was missing which has been added as per PR #2373
