### ISSUE TITLE
CA deployments are not exposed in Kubernetes. Kubectl command is required to manually add them.

### ISSUE THREAD

**Issue by icordoba** [hyperledger/bevel#2371]
**Describe the bug**
In the deployment process using , the ca deployments for all organizations are not exposed so they pods are not visible to the rest of the network. I need to manuall add them using:

kubectl expose deployment ca --type=ClusterIP -n ORG1-net
kubectl expose deployment ca --type=ClusterIP -n ORG2-net

**To Reproduce**
1. Deploy the network from bevel running in a local docker instance using: ansible-playbook  platforms/shared/configuration/site.yaml -e "@./build/network.yaml" 
2. Wait for the pause for CA generation time. Verify that no CA deployment is exposed. 
3. Network will fail as CAs are not accessible to the rest of resources in the namespace, given they are not exposed as ClusterIP (nor any other type, Nodeport, ...)

**Expected behavior**
Commands indicated above should not be required to have CAs exposed in the internal IP network of the cluster.

**Environment (please complete the following information):**
Azure AKS
Hyperledger Fabric 2.2.2
2 Organization network, one orderer one peer.

**Comment by sownak** [comment]
@icordoba This is happening with haproxy or no proxy?

**Comment by icordoba** [comment]
No proxy. (BTW, no errors or warnings shown in the process)

**Comment by sownak** [comment]
CA servers are deployed correctly when using the charts in `platforms/hyperledger-fabric/charts/ca`. This has been tested with latest code and no proxy setting.
