### ISSUE TITLE
Network Schema doesnt support fabric node chaincode

### ISSUE THREAD

**Issue by cw6365** [hyperledger/bevel#2375]
**Describe the bug**

The network schema doesn't have node in the enum so fails the build, it says on the docs that it's supported? Is it?

https://github.com/hyperledger/bevel/blob/28ff161b268d5869c131be5c81c86eaebe602e3e/platforms/network-schema.json#L677

I'll add a PR if it is.

**Comment by sownak** [comment]
Seems like a miss, please send a PR. I will assign this to you.
