### ISSUE TITLE
The Ansible playbook fails when checking for the installation of kubectl.

### ISSUE THREAD

**Issue by GowthamParamasivam** [hyperledger/bevel#2446]
**Describe the bug**
When I attempt to execute the playbook for setting up the initial network using the following command [link](https://hyperledger-bevel.readthedocs.io/en/latest/operations/upgrade_fabricnetwork.html), the playbook fails when checking the installation of kubectl.

**Expected behavior**
The Ansible playbook must execute and create pods on the cluster.

**Screenshots**
<img width="894" alt="image" src="https://github.com/hyperledger/bevel/assets/43418883/6049b6a9-1938-4f0a-8c78-9b6593d37028">

**Environment (please complete the following information):**
 - OS: Mac OS, M1

**Comment by GowthamParamasivam** [comment]
The reason for the bug is kubectl doesn't support the --short command mentioned in the following [file](https://github.com/hyperledger/bevel/blob/c79bc40495d111ab48b800605cda11060cd9a004/platforms/shared/configuration/roles/setup/kubectl/tasks/main.yaml#L60), if we remove the --short from the ansible there wont be an issue.

<img width="894" alt="image" src="https://github.com/hyperledger/bevel/assets/43418883/d29a271b-f600-45ff-b0b7-ea27eb4ce2e9">

**Comment by sownak** [comment]
@GowthamParamasivam  Which version of kubectl are you using?

**Comment by GowthamParamasivam** [comment]
My kubectl version is 1.28.4

<img width="894" alt="image" src="https://github.com/hyperledger/bevel/assets/43418883/173f8c16-bf3b-43aa-83d4-11e2ba9d8a73">

**Comment by sownak** [comment]
We only support kubernetes version till 1.24 for now.

**Comment by GowthamParamasivam** [comment]
Oh Okay. Then will close the issue with this comment.
The reason for this issue is I tried with the kubectl client version 1.28 which is not supported by bevel currently, current supported version is till 1.24.
