### ISSUE TITLE
chaincode commit not working

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2451]
**Describe the bug**
Chaincode commit job `fabric-chaincode-commit` is failing in the init container. Job throws an error while storing certificates in the vault.

```
Vault write API call response: {"errors":["error parsing JSON"]}
```

**To Reproduce**

**Expected behavior**
Job should commit chaincode

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by mgCepeda** [comment]
I'll take this issue
