### ISSUE TITLE
update(doc): configuration files section under guides tab

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2465]
### Description
As a developer I want to update the configuration files section for each of the platforms

- [x] Quorum
- [x] Besu
- [x] Fabric
- [x] R3 Corda Ent
- [x] R3 Corda OS
- [x] Indy
- [ ] Substrate 

### Acceptance Criteria
1. Update with the new format and doc look

**Comment by suvajit-sarkar** [comment]
Have picked up the HL Fabric configuration file section

**Comment by mgCepeda** [comment]
I'll take fabric

**Comment by mgCepeda** [comment]
I'll pick Fabric

**Comment by mgCepeda** [comment]
I'll take Indy

**Comment by suvajit-sarkar** [comment]
Reopening this issue as substrate is pending.

**Comment by suvajit-sarkar** [comment]
Closing this issues as the substrate doc changes will be on #2547
