### ISSUE TITLE
policy_type variable undefined

### ISSUE THREAD

**Issue by Linkadi98** [hyperledger/bevel#2473]
**Describe the bug**
When I run `run.sh` script, task Create policy for Access Control shows error `The error was: 'policy_type' is undefined`

**To Reproduce**
1. Prepare a cluster by Minikube with docker driver
2. Prepare Vault by Helm 
3. Follow instruction to setup build folder
4. Build docker image and run container

**Expected behavior**
Go to the next step

**Screenshots**
<img width="1526" alt="image" src="https://github.com/hyperledger/bevel/assets/36079989/60b411c5-3ae9-4de3-806f-562d3e9d8f81">

**Environment (please complete the following information):**
 - OS: Ubuntu server with public ip
 - Version 22.04 LTS 

**Additional context**
I follow the instruction in the `tutorial` folder to setup environment

**Comment by Linkadi98** [comment]
As the log says, the `policy_templates` missing `policy_type` as below

`policy_templates:
        quorum: quorum-policy.tpl
        besu: besu-policy.tpl
        cordaos: cordaos-policy.tpl
        fabric: fabric-policy.tpl
        r3-corda-ent: r3-corda-ent-policy.tpl
`

This config doesn't contain `policy_type` field, I also cannot find the fabric-policy.tmp file in anywhere

**Comment by suvajit-sarkar** [comment]
the policy_type variable is defined in the calling role. In your case, I assume you trying to deploy Fabric network. The policy_type is defined here
https://github.com/hyperledger/bevel/blob/487f659b7e3637db3f98383b50ebe16b158392c8/platforms/hyperledger-fabric/configuration/deploy-network.yaml#L62

**Comment by suvajit-sarkar** [comment]
What branch/tag are you using ?

**Comment by Linkadi98** [comment]
I saw policy_type in this file before, but the log says it is not defined, so how do I fix this error? Before the latest release, I have never seen this error 😗

**Comment by Linkadi98** [comment]
> What branch/tag are you using ?

I use develop branch with the latest code

**Comment by Linkadi98** [comment]
I just check the code in main branch and everthing is okay, the issue only appears at develop branch

**Comment by suvajit-sarkar** [comment]
Looks like valid issue on dev branch

**Comment by Linkadi98** [comment]
Today I try to run network with minikube driver=none, which means I use directly the host to make a cluster and the issue apprears after this config, and I also use the latest code at main branch.
@suvajit-sarkar

**Comment by saikumarbommakanti** [comment]
I am working on this
