### ISSUE TITLE
No supplychain-net-CA.key created during TASK Check if CA key already exists in vault

### ISSUE THREAD

**Issue by Linkadi98** [hyperledger/bevel#2476]
**Describe the bug**
I don't know if this is a bug or I miss some steps but I have followed the doc to make the network run. This issue comes when there is no `secretsv2/crypto/ordererOrganizations/supplychain-net/ca` folder created in Vault, and I cannot find any task that creates this folder

**To Reproduce**
Follow the doc to create network by docker

**Expected behavior**
Move to next step

**Screenshots**
<img width="1524" alt="image" src="https://github.com/hyperledger/bevel/assets/36079989/bb2c355e-ce15-4206-9476-a2533a6ef261">

**Environment (please complete the following information):**
 - OS: Ubuntu server with public ip
 - Version 22.04 LTS

**Additional context**
I use minikube cluster with driver=docker and use the latest code on main branch

**Comment by Linkadi98** [comment]
I notice that all the steps right before this error return `Conditional result was False` like below
<img width="1526" alt="image" src="https://github.com/hyperledger/bevel/assets/36079989/8d0c16d4-60de-45f9-9676-350ab7cde629">

**Comment by sownak** [comment]
@Linkadi98 Have you gone through https://hyperledger-bevel.readthedocs.io/en/latest/tutorials/bevel-minikube-setup/#execute-provisioning-script ??

**Comment by Linkadi98** [comment]
Yes I have followed this doc, also I did read all the docs inside tutorial folder

**Comment by sownak** [comment]
![image](https://github.com/hyperledger/bevel/assets/20537268/6ad2211a-eaec-419b-8e47-bbe1581d1d43)

**Comment by Linkadi98** [comment]
> ![image](https://private-user-images.githubusercontent.com/20537268/296206943-6ad2211a-eaec-419b-8e47-bbe1581d1d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTU1MjUsIm5iZiI6MTcwNTA1NTIyNSwicGF0aCI6Ii8yMDUzNzI2OC8yOTYyMDY5NDMtNmFkMjIxMWEtZWFlYy00MTliLThlNDctYmJlMTU4MWQxZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDEwMjcwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZDNkZDNkYzBiZjdmMzMzZjc3MGE1NzBlOTYwZjFmNzA4ZGI3NWMyNmM5MjY1OGU0YWUxMDJjZTgzMzY2OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qg5X918dBoT9Uu9BV1pypp-OafAjTLeDiHo0OVTQshA)

I see that, but this issue still apprears even if I follow the Excecute provisioning script

**Comment by sownak** [comment]
So, is the ansible playbook failing when you see the "error" you mentioned. I can clearly see that it was ignored.

**Comment by Linkadi98** [comment]
No, the ansible playbook keeps running but after that it fails at step `Wait for Job supplychain-cacerts-job in supplychain-net` because of timeout after retrying this job, sorry about wrong posting error log, ansible playbook fails at this 
<img width="1529" alt="image" src="https://github.com/hyperledger/bevel/assets/36079989/390468a1-cc67-459a-a1a2-cf11da62bfa0">
and this is error log 
[error_log.txt](https://github.com/hyperledger/bevel/files/13917945/error_log.txt)

**Comment by sownak** [comment]
This is not a bug or issue, there have been many discussions on this on Discord. Simply put, your supplychain-cacerts-job is not running successfully for a reason, you have to check the logs of that job on Kubernetes to figure out what is wrong.
Also, please check https://hyperledger-bevel.readthedocs.io/en/latest/contributing/asking-a-question/ rather than creating a "Issue".
