### ISSUE TITLE
update(doc): operations section under guides tab

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2483]
### Description
As a developer I want to update the operations section with the new doc formatting

e.g. - https://hyperledger-bevel.readthedocs.io/en/latest/guides/fabric/add-cli/

- [x] Besu
- [x] Quorum
- [x] Fabric
- [x] R3 Corda
- [x] R3 Corda Ent 
- [x] Indy

### Acceptance Criteria
1. All sample configuration are presents
2. The operation guides uses new format of referring directly the sample file lines

**Comment by mgCepeda** [comment]
I'll take fabric

**Comment by mgCepeda** [comment]
I'll take Indy
