### ISSUE TITLE
epic: platform deployments using just helm commands and charts

### ISSUE THREAD

**Issue by saurabhkumarkardam** [hyperledger/bevel#2484]
**As Developers, we want to implement deployment of platforms using just helm charts**

**Few of the key improvements in the platform's charts folder as follows:**
- Update `parameters table` to accurately reflect variable hierarchy and use `camelCase` for parameter/variable names.
- Align the READMEs of a specific platform with the structure and design of `BESU` READMEs.
- Implement hook concept to delete all the supported resources of a chart while doing the network reset
- Utilize `helpers.tpl` to assign the deployment name instead of metadata section in template (.tpl) and values.yaml files.
- Organize common configuration variables, like those associated with Vault and Cluster, under the `global` section in template (.tpl) and values.yaml files. Ensure these variables are used with the updated hierarchy within the respective chart.
- Implement chart dependencies and  use pre install hook concept to create prerequisite Kubernetes  resources and run one time tasks  

**Required testing**:
- Perform Helm lint manually to quickly validate the chart, followed by the successful network deployment and reset using just helm charts and commands.
- For any concerns and their solutions, please follow the Besu Platform.

**This issue needs to be fixed for the following platforms**:
- [x] Besu @sownak 
- [x] Quorum @saurabhkumarkardam 
- [x] Fabric @mgCepeda 
- [x] R3-Corda-Ent @suvajit-sarkar 
- [x] R3-Corda @sownak 
- [x] Substrate @saurabhkumarkardam and @saikumarbommakanti

**Comment by suvajit-sarkar** [comment]
The substrate work scope for this issue is complete and available on the pr #2541
