### ISSUE TITLE
Incorrect storage class name

### ISSUE THREAD

**Issue by adityajoshi12** [hyperledger/bevel#2513]
**Describe the bug**

**To Reproduce**

Helm chart `bevel-storageclass` is creating storage class with incorrect name. Example it should create storage class with name `bevel-storageclass-org1-azure-storageclass` while the check in the playbook is for the `org1 -azure-storageclass`.

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. MacOS]

**Additional context**

**Comment by suvajit-sarkar** [comment]
@adityajoshi12 can you give more details ? also mention the branch.

**Comment by suvajit-sarkar** [comment]
Kindly use the main branch, until all changes in develop branch is complete.

**Comment by adityajoshi12** [comment]
Yes, it was a bug in develop branch
