### ISSUE TITLE
update(besu, quorum): ansible playbooks and roles to use the new standalone helm charts

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2546]
### Description
As a developer I want to cleanup, update and test ansible playbooks and roles that the Besu and Quorum networks can be deployed using the new standalone helm charts

### Acceptance Criteria
1. Network deployed using ansible playbook (No Proxy No Vault and with Proxy and Vault)
2. Network cleanup using ansible playbook

**Comment by alvaropicazo** [comment]
I'lle working on this
