### ISSUE TITLE
update(substrate): ansible playbooks and roles to use the new standalone helm charts

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2547]
### Description
As a developer I want to cleanup, update and test ansible playbooks and roles so that the Substrate network can be deployed using the new standalone helm charts

### Acceptance Criteria
1. Network deployed using ansible playbook (Proxy and Vault, No proxy)
2. Network cleanup using ansible playbook
3. Update the configuration files and readthedocs

**Comment by saurabhkumarkardam** [comment]
I would like to work on it.
