### ISSUE TITLE
update(r3-corda-ent): ansible playbooks and roles to use the new standalone helm charts

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2548]
### Description
As a developer I want to cleanup, update and test ansible playbooks and roles so that the R3 Corda Enterprise network can be deployed using the new standalone helm charts

### Acceptance Criteria
1. Network deployed using ansible playbook (No Proxy No Vault and with Proxy and Vault)
2. Network cleanup using ansible playbook
3. Add operation playbooks (add node/notary and cordapps)

**Comment by saikumarbommakanti** [comment]
I will try this one
