### ISSUE TITLE
update(fabric): ansible playbooks and roles to use the new standalone helm charts

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2556]
### Description
As a developer I want to cleanup, update and test ansible playbooks and roles so that the Hyperledger Fabric network can be deployed using the new standalone helm charts

### Acceptance Criteria
1. Network deployed using ansible playbook (with Proxy/No Proxy and Vault)
2. Network cleanup using ansible playbook

**Comment by alvaropicazo** [comment]
I'll be working on this task
