### ISSUE TITLE
RLPx Handshake Error in Quorum Validator Nodes

### ISSUE THREAD

**Issue by alvaropicazo** [hyperledger/bevel#2563]
**Describe the bug**
I am trying to deploy quorum validator nodes following the documentation from the charts, and after my validator pod is running, I can see the following error
![Screenshot 2024-05-17 at 12 21 05](https://github.com/hyperledger/bevel/assets/76157062/78721f92-9d24-4b40-84a5-a88d92554869)

**To Reproduce**
1. Deploy the genesis chart
2. Deploy the validator chart with ambassador & vault
3. Check the logs of the pod where the validator is running

**Comment by suvajit-sarkar** [comment]
Closing this issues as this error might be due to use of proxy and how quorum translates the addresses. From a network level things are working fine, p2p rplx comm. is happening and blocks are getting added.
