### ISSUE TITLE
Update `refresh-certificates` playbook

### ISSUE THREAD

**Issue by amozghovyi** [hyperledger/bevel#2564]
**Is your feature request related to a problem? Please describe.**
We tested the certificate renewal procedure and found some possible playbook errors and unstable behavior. Our environment- Fabric v2.5.4, Bevel v1.0.0 (from github tag `v1.0.0.0`).

**Describe the solution you'd like**
Please check the following things in `refresh-certificates` playbook:

- ["Create CA tools for each organization"](https://github.com/hyperledger/bevel/blob/67ca0c9b5e96f764abdab719a2b9d8412f1cd553/platforms/hyperledger-fabric/configuration/refresh-certificates.yaml#L41) task should have a variable `sc_name: "{{ component }}-bevel-storageclass"` (same as in deploy-network playbook)

- Looks like [sys_channel_name](https://github.com/hyperledger/bevel/blob/67ca0c9b5e96f764abdab719a2b9d8412f1cd553/platforms/hyperledger-fabric/configuration/refresh-certificates.yaml#L67) variable should be `masterchl` instead of `syschannel`
- [Create all orderers](https://github.com/hyperledger/bevel/blob/67ca0c9b5e96f764abdab719a2b9d8412f1cd553/platforms/hyperledger-fabric/configuration/refresh-certificates.yaml#L94) task should have a variable `channel_name` because task `Fetch the genesis block from vault` in role `create/orderer` requires a channel name.
- Looks like `channel.channel_name` variable in [Create genesis block](https://github.com/hyperledger/bevel/blob/67ca0c9b5e96f764abdab719a2b9d8412f1cd553/platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/main.yaml#L43) and [Write genesis block to Vault](https://github.com/hyperledger/bevel/blob/67ca0c9b5e96f764abdab719a2b9d8412f1cd553/platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/main.yaml#L48) tasks in role [create_channel_block](https://github.com/hyperledger/bevel/blob/v1.0.0.0/platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/main.yaml) should be different (maybe `sys_channel_name`). Otherwise an error ` channel is undefined` occurs.

After applying these changes we were able to execute the playbook successfully.
But after a couple of days we tried to launch the same playbook (without any additional changes) to ensure that all certificates have been renewed. And we have an error (some lines have been omitted):
```
TASK [create/refresh_certs/create_channel_block : Fetch masterchl configuration block from the blockchain] ***
task path: /var/jenkins_home/jobs/Automation/jobs/Renew_Certs/workspace/bevel/platforms/hyperledger-fabric/configuration/roles/create/refresh_certs/create_channel_block/tasks/get_update_block.yaml:8

fatal: [localhost]: FAILED! => {"attempts": 7, "changed": true, "cmd": "export PEER_CLI=$(KUBECONFIG=/root/.kube/config kubectl get po -n <ordrer_org>-net | grep \"cli\" | head -n 1 | awk '{print $1}')\nKUBECONFIG=/root/.kube/config kubectl exec -n <orderer_org> ${PEER_CLI} -- peer channel fetch config <orderer_2>_masterchl_config_block.pb -o <orderer_1>.<orderer_org>-net:7050 -c masterchl --tls --cafile ${ORDERER_CA}
---
readBlock\u001b[0m -> **Expect block, but got status: &{NOT_FOUND}**\n**Error: can't read the block: &{NOT_FOUND}**\
```

As I said above, the first launch of the playbook was successful.

**Describe alternatives you've considered**

**Additional context**

**Comment by alvaropicazo** [comment]
I'll be working on this feature
