### ISSUE TITLE
docs: update platform operations guide

### ISSUE THREAD

**Issue by suvajit-sarkar** [hyperledger/bevel#2585]
### Description
As a developer I want to update the platforms guide so that it follow the new format having `Using helm install` section.

https://hyperledger-bevel.readthedocs.io/en/develop/guides/fabric/add-cli/

### Acceptance Criteria
1. Platforms test for the ops and docs updated.

**Comment by alvaropicazo** [comment]
# Platforms 

## Hyperledger Fabric (2.5.x)

- [x] Normal Deployment
- [x] Add Channel
- [x] ~~Add Org~~
- [x] ~~Add Peer~~
- [x] ~~Add orderer~~
- [x] ~~Add orderer org~~

## Hyperledger Besu

- [ ] Normal Deployment
- [ ] Add Validator
- [] Add Org
- [] Add Member Org

## Hyperledger Indy

- [ ] Normal Deployment

## Quorum

- [ ] Normal Deployment

## R3 Corda

- [ ] Normal Deployment

## R3 Corda Ent

- [ ] Normal Deployment

## Substrate

- [ ] Normal Deployment
