### ISSUE TITLE
No bevel-build image tagged for linux/arm64/v8 - gives error when following guide

### ISSUE THREAD

**Issue by michaelkhalsa** [hyperledger/bevel#2602]
**Describe the bug**
When following the online guide for installing HLF on Minikube on a Mac (apple silicon).
everything works up to the point of fetching the bevel-build, where I get an error:

1.1.0: Pulling from hyperledger/bevel-build
docker: no matching manifest for linux/arm64/v8 in the manifest list entries.

I first tried :latest, then :stable, and finally various versions. Same response.

**To Reproduce**
1. Follow the guide https://blockchain-automation-framework.readthedocs.io/en/latest/tutorials/bevel-minikube-setup/#__tabbed_2_2)
2. Setup all prerequisites, such as start minikube (using docker driver), HashiCorp vault, etc.
3. When reached the stage to fetch the package to mount, through script:

docker run -it -v /mnt/bevel:/home/bevel/ --network="host" ghcr.io/hyperledger/bevel-build:latest bash

4. gives error as per above. Tried using later versions as well (note: that version 1.0.0 is still tagged as latest).

**Expected behavior**
Either mention in the guide if not supported on an apple silicon Mac, or a build tagged with support for it.

**Environment (please complete the following information):**
 - OS: Mac Sonoma on M3
 - Version latest stable
 - latest docker, vault, Kubernetes, kubectl, etc.

**Additional context**
Thanks for all of the work this team is doing!

**Comment by sownak** [comment]
1.1.0 and stable both are available at https://github.com/hyperledger/bevel/pkgs/container/bevel-build 
Does your network pull docker images from any other ghcr successfully?

**Comment by michaelkhalsa** [comment]
Thanks!

I was able to work around it by adding a --platform="linux/amd64" switch to the docker run command, which then simply gave a warning (as on an arm64 Mac), but did grab the image successfully.

Please ignore the following if wrong place to ask, and I can go to discord.
In the tutorial, this command is given

docker run -it -v /mnt/bevel:/home/bevel/ --network="host" ghcr.io/hyperledger/bevel-build:latest bash

However, is the source and destination switched?, as there is no mnt directory in local machine, only on the proxy. I replaced source: /mnt/bevel with $(pwd) and left destination: /home/bevel as is (because the run script refers to home/bevel in the path, and not mnt/bevel).

also added the --platform="linux/amd64" tag, which works even though wrong platform for me (on apple silicon).

This worked up to a point, and failed when testing the kubectl installation (man.yaml:59)
The connection to the server localhost:8080 was refused

Guessing it is not using the config file specified in build directory (which is there). Maybe I started minikube from wrong directory??? I did specify the ip as a switch when starting minikube. Is there something I missed? I am new to Kubernetes and minikube. minicab ip view --> 192.168.49.2  My local machine is 192.168.68.54 (which is what I specified, also tried 127.0.0.1)

**Comment by michaelkhalsa** [comment]
Set everything up on an old intel dell gps with ubuntu 22.04 16gb ram
And was more careful to place build, bin, config.hcl, ... in home/project/bevel

Everything working up to same point where it was failing on Mac (as per previous comment) when testing KubeCtl (minikube), where connection to the server localhost:8080 was refused.

I bet there is something simple I missed, but not sure where to go with it.

Note: typo in the prequisites, says helm >= 3.6, but the latest version is 3.15

**Comment by suvajit-sarkar** [comment]
Closing this issue. Please reopen it if the issue persists
