### ISSUE TITLE
Make docker creds section in network.yaml as optional in Hyperledger Fabric

### ISSUE THREAD

**Issue by jagpreetsinghsasan** [hyperledger/bevel#613]
Currently, we don't have an option to exclude docker credentials from network.yaml
The docker credentials are used to create a kubernetes secret (docker cred template) which is used to pull images with docker credentials.
With the inclusion of images over a public dockerhub registry, we dont need the docker username & password section in the network.yaml, the regcred and thus there is no need to pull the image with docker creds.

The changes required are:

- In the file **hyperledger-fabric/configuration/roles/setup/vault_kubernetes/tasks/main.yaml**, change the second last task named "**Checking if the docker credentials already exists**" and the last task named **"Create the docker pull credentials**" to run only if network.docker.username && network.docker.password are defined and are not empty. To check if a variable (network.docker.username) is defined and not empty, you can use the code `network.docker.username | default('', true) | trim != ''`

- For the charts, you need to a put a condition to use **imagePullSecrets** only when `network.docker.username | default('', true) | trim != ''` and `network.docker.password | default('', true) | trim != ''`

	The following charts are required to be changed for Hyperledger Fabric

	- [ ] anchorpeer chart

	- [ ] ca chart

	- [ ] create_channel chart

	- [ ] fabric_cli chart

	- [ ] install_chaincode chart

	- [ ] instantiate_chaincode chart

	- [ ] invoke_chaincode chart

	- [ ] join_channel chart

	- [ ] orderernode chart

	- [ ] peernode chart

	- [ ] upgrade_chaincode chart

	- [ ] verify_chaincode chart

- Test the network by running network till chaincode instantiation.

**Comment by sailajakommineni** [comment]
i will look into this.
