### ISSUE TITLE
Add cordapps molecule test scenario in Corda

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#629]
### Description
As a developer I want to run molecule test so that I can test my `deploy/cordapps` role.

### Acceptance Criteria
1.Molecule tests should cover `deploy/cordapps` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by suvajit-sarkar** [comment]
Deploy corDapps process has been changed .. the roles might not be in use anymore

**Comment by sownak** [comment]
Closed as this role is not used anymore
