### ISSUE TITLE
Add channels molecule test scenario in Fabric

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#637]
### Description
As a developer I want to run molecule test so that I can test my `create/channels` role.

### Acceptance Criteria
1.Molecule tests should cover `create/channels`, `create/channels_join`, `create/anchorpeer` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by suvajit-sarkar** [comment]
Closing the issue we would not be using molecule
