### ISSUE TITLE
Add chaincode molecule test scenario in Fabric

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#638]
### Description
As a developer I want to run molecule test so that I can test my `create/chaincode` role.

### Acceptance Criteria
1.Molecule tests should cover `create/chaincode/install`, `create/chaincode/instantiate`, `create/chaincode/invoke`, `create/chaincode/upgrade` and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by suvajit-sarkar** [comment]
Closing the issue we would not be using molecule
