### ISSUE TITLE
Use Bevel release numbers to tag Indy docker images created in Bevel

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#690]
### Description
As a user I want to tag the indy docker images with BAF release numbers so that they are easy to build and maintain by us.

The hyperledgerlabs/indy-node, indy-key-mgmt and indy-ledger-txn are tagged as per Indy release numbers. This can get hard to maintain and other users will be confused with them. Tag these images with BAF release tags like 0.3.0.0 as done for Corda and express-api. Then add a mapping vars in the ansible playbooks. 

Check for example in examples/supplychain-app/configuration/roles/create/corda/expressapi/ role.

### Acceptance Criteria
1. All Indy version tags replaced with BAF release tags
2. Correct mapping file created for Indy

**Comment by manikanta-darsi** [comment]
please assign it to me.
