### ISSUE TITLE
Add Indy molecule tests in Git Actions

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#734]
### Description
As a developer I want to run all Indy Molecule test Scenarios so that the Git Actions script is complete for Indy.
Add a condition so that the Indy tests are run only when the check-in has a "[indy]" in the PR title

### Acceptance Criteria
1. Git Actions test should run for Fabric when commit message has "[indy]"
2. All Indy molecule test scenarios should be run

**Comment by suvajit-sarkar** [comment]
Closing issue, as molecule tests wont be used anymore
