### ISSUE TITLE
Add Supplychain-app molecule tests

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#736]
### Description
As a developer I want to run default molecule test so that I can test my ansible scripts for Supplychain-app.

This test should run for all roles in examples/supplychain-app/configuration.
Divide the story into separate scenarios based on complexity.

### Acceptance Criteria
1.Molecule tests should cover all roles in the deploy-supplychain-app.yaml and related roles
2. Verification step should be configured.
3. Tests should complete successfully

**Comment by S-Eemani** [comment]
@sownak I would like to work on this.

**Comment by sownak** [comment]
@S-Eemani Please do.. the code base has moved to bevel-samples though. Please comment then I would move this issue to bevel-samples and assign to you.
