### ISSUE TITLE
Add Application molecule tests in GitActions

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#738]
### Description
As a developer I want to run all Example application Molecule test Scenarios so that the Git Actions flow is complete for Applications.
Add a condition so that the Application tests are run only when the check-in has a "[application]" in the commit message

### Acceptance Criteria
1. GitActions test should run for Sample applications when commit message has "[application]"
2. All Application molecule test scenarios should be run for both supplychain and identity. (this can be separated if the tests take more than 5 minutes to run)
3. Tests should run parallelly for supplychain and identity app

**Comment by sownak** [comment]
@NIKITA-M-VERMA the sample application has now been moved to bevel-samples, you can take this issue. It is open to take up.

**Comment by NIKITA-M-VERMA** [comment]
Greetings @sownak 
I am new to community , can you please guide me out how to proceed furthur .
I am a new contributor can you please give me your piece of advice ,it will be really helpful for me .

**Comment by sownak** [comment]
@NIKITA-M-VERMA This issue will now be on Bevel-samples repo, if you are still interested to work, please comment then I will move this to the bevel-samples repo and assign to you.

**Comment by NIKITA-M-VERMA** [comment]
Thanks @sownak for information 
 I am interest to take up this issue even now 
Can you please assign this issue to me .
