### ISSUE TITLE
Add Indy image build in Git Actions

### ISSUE THREAD

**Issue by sownak** [hyperledger/bevel#742]
### Description
As a developer I want to build Indy image for a specific Indy version and tag it according to Bevel release number, so that all build commands are available as code.
Now the Indy image is built from Docker hub automated build where it does not accept Build version.

### Acceptance Criteria
1. Correct Indy image build is available on ghcr.io
2. Git Action succeeds

**Comment by manikanta-darsi** [comment]
Please assign it to me.
